services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kgagliar/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kgagliar/data/mariadb

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
